server:
  port: 8080
  servlet:
    context-path: /demo
qiniu:
  ## 此处填写你自己的七牛云 access key
  accessKey:
  ## 此处填写你自己的七牛云 secret key
  secretKey:
  ## 此处填写你自己的七牛云 bucket
  bucket:
  ## 此处填写你自己的七牛云 域名
  prefix:

# 上传配置 servlet multipart
spring:
  servlet:
    multipart:
      enabled: true
      location: E:\dev_workspace\spring-boot-start\spring-boot-start-upload
      file-size-threshold: 5MB
      max-file-size: 20MB
