server:
  port: 8080
  servlet:
    context-path: /spring-boot-start-mq

spring:
  rabbitmq:
    host: 192.168.100.171
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
