server:
  port: 80
  servlet:
    context-path:

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql//49.235.210.101:3306/spring-boot-start
    data-username: root
    data-password: ganquanzhong

  redis:
    host: 192.168.100.171
    password:
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    # database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

#  cache:
#    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
#    type: redis

logging:
  level:
    com:
      gqzdev:
        cache:
          redis:
            mapper: debug

